env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
globals:
  _: "readonly"
rules:
  import/prefer-default-export: "off"
  indent:
    - "error"
    - "tab"
  no-tabs: off
  no-unused-vars:
    - "error"
    - varsIgnorePattern: "_"
  import/extensions:
    - "error"
    - ts: never
  no-underscore-dangle: off
